### ISSUE TITLE
zimbra 7.2.7 + zsugar 1.4.16 not working

### ISSUE THREAD

**Issue by rspshotgun** [irontec/zsugar#17]
Upon trying to load the zimlet - we're met with this error in the mailbox.log...

Any idea how to resolve?  its using the latest provided zip file

2016-09-19 18:10:05,028 WARN  [btpool0-426795://zimbra.domain.com.au/service/zimlet/com_irontec_zsugar/redirect.jsp] [] log - /service/zimlet/com_irontec_zsugar/redirect.jsp
org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP

PWC6197: An error occurred at line: 17 in the jsp file: /com_irontec_zsugar/redirect.jsp
PWC6199: Generated servlet error:
Base64Coder cannot be resolved

	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:123)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:296)
	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:376)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:814)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:218)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:422)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:330)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
	at com.zimbra.cs.zimlet.ZimletResources.service(ZimletResources.java:130)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.zimbra.cs.zimlet.ZimletFilter.doFilter(ZimletFilter.java:240)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:79)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.zimbra.cs.servlet.ThrottlingFilter.doFilter(ThrottlingFilter.java:71)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:114)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:218)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:422)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.handler.rewrite.RewriteHandler.handle(RewriteHandler.java:230)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.handler.DebugHandler.handle(DebugHandler.java:77)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:585)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:988)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:415)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:429)
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451)

**Comment by Kaian** [comment]
Hi @rspshotgun 

Umm, thats strange, the class that is unable to find (Base64Coder) is distrubuted with the zip in `base64coder.jar` and it haven't change since the first version of the zimlet..

Did you restarted your mailbox after installing the zimlet?
You can see [INSTALL](https://github.com/irontec/zsugar/blob/master/doc/INSTALL) for instructions of how to do it from the command line.

**Comment by rspshotgun** [comment]
Hi 

thanks for you prompt reply. Is restarting zmmailboxd required? We've not had to do that before for other zimlets. However I will try that when it is convenient to restart it

Cheers
Spyro

**Comment by Kaian** [comment]
Hey!

Yep, its required at least in the initial installation (usually not required for upgrades).

The reason is that zsugar uses a JSP file to proxy requests to SugarCRM. This improves the management of attachments, because they are sent directly from zimbra server and not from user browser.

Most zimlets don't use JSP, but just javascript, so they don't require any mailboxd restart.

Best regards!

**Comment by rspshotgun** [comment]
Ok great no problems. I'll give that a go when it's convenient to restart :) Thankyou

**Comment by rspshotgun** [comment]
Its all working fine after restarting the mailboxd service.. thankyou :) 

----- Original Message -----

**Comment by Kaian** [comment]
Nice! You welcome!
